version: "3.8"

services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edu-plan
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d course_api_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      target: build
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://auth_user:auth_password@db:5432/course_api_dev
      JWT_SECRET: super-secret
      PORT: 3333
    ports:
      - "3333:3333"
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    command: npm run dev

volumes:
  postgres_data:
